server.port: 8080

spring:
  activemq:
    broker-url: tcp://1.94.136.58:61616  #activeMQ的ip和端口号
    user: admin   #activeMq账号
    password: admin #activeMq密码
    queue-name: active.queue #消息队列
    topic-name: active.topic #消息广播
    receiver-queue: active.queue
    pool:
      enabled: true       #连接池启动
      max-connections: 10 #最大连接数
    #本地开发关闭jms
    jms:
      enable: true

  Baidu:
    appid: 20240407002016334
    key: T52E3n0ecEB7Jdo4RQ0i
    url: https://fanyi-api.baidu.com/api/trans/vip/translate

  datasource:
    url: jdbc:mysql://1.94.12.85:3306/chat
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
